packages:
  - ./app
  - ./worker

ignoredBuiltDependencies:
  - bufferutil
  - core-js-pure
  - es5-ext
  - esbuild
  - utf-8-validate
  - vue-demi

onlyBuiltDependencies:
  - "@parcel/watcher"
  - nx
  - postinstall-postinstall
  - bufferutil
  - core-js-pure
  - es5-ext
  - esbuild
  - utf-8-validate
  - vue-demi
